from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


ROOT = Path("/Users/hi/projects/nepalEnergy")
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed" / "corridor_tracing" / "manifests"


SOURCES: list[dict[str, Any]] = [
    {
        "source_id": "mca_annex_d1_alignment_maps",
        "title": "MCA-Nepal Annex D-1 Alignment Maps",
        "path": RAW / "corridor_tracing" / "mca" / "mca_annex_d1_alignment_maps.pdf",
        "url": "https://mcanp.org/Content/GetPdf?filePath=%2FMCANP%2FEIAReports%2FAnnexD_1_Alignment-Maps.pdf&section=EIAReports&guid=90d56f40-0b72-4cb0-9e2b-fa8eeaba72d3",
        "source_type": "pdf",
        "document_class": "alignment_atlas",
        "primary_use": "trace_grade",
        "note": "193-page A3 alignment atlas for the MCA central 400 kV corridor. Exact sheet ranges still need source-by-source confirmation.",
    },
    {
        "source_id": "world_bank_hddtl_rap",
        "title": "World Bank Hetauda-Dhalkebar-Duhabi RAP",
        "path": RAW / "corridor_tracing" / "world_bank" / "world_bank_hddtl_rap.pdf",
        "url": "https://documents1.worldbank.org/curated/en/522221483681808545/pdf/IPP476-v2-Box396344B-PUBLIC-disclosed-1-5-17.pdf",
        "source_type": "pdf",
        "document_class": "rap",
        "primary_use": "trace_grade",
        "note": "Best public route-map packet for HDDTL; includes overview map figure and detailed corridor description.",
    },
    {
        "source_id": "rpgcl_transmission_network_map_revised1",
        "title": "RPGCL Nepal Transmission Network Map Revised 2021",
        "path": RAW / "corridor_tracing" / "rpgcl" / "nepal_transmission_network_map_revised1.pdf",
        "url": "https://www.rpgcl.com/storage/listies/November2021/nepal-tranmission-network-map-revised1.pdf",
        "source_type": "pdf",
        "document_class": "geospatial_vector_map",
        "primary_use": "trace_grade",
        "note": "Official ArcMap geospatial PDF with extractable vector transmission linework and layer metadata. This is now the main extraction source for the four traced corridor outputs committed in the repo.",
    },
    {
        "source_id": "mca_project_summary_report",
        "title": "MCA-Nepal Project Summary Report",
        "path": RAW / "corridor_tracing" / "mca" / "mca_project_summary_report.pdf",
        "url": "https://mcanp.org/Content/GetPdf?filePath=%2FMCANP%2FFeasibilityStudiesReports%2FVolume-8-Project-Summary-Report.pdf&section=FeasibilityStudiesReports&guid=02f6a408-fd36-4732-a580-0ae2af8b35ae",
        "source_type": "pdf",
        "document_class": "feasibility_summary",
        "primary_use": "naming_reference",
        "note": "Useful for reconciling older Naubise-based nomenclature against the current Ratmate-centered MCA corridor naming.",
    },
    {
        "source_id": "moewri_ipsdp_exec_summary_2025",
        "title": "MoEWRI IPSDP Executive Summary 2025",
        "path": RAW / "corridor_tracing" / "moewri" / "moewri_ipsdp_exec_summary_2025.pdf",
        "url": "https://giwmscdnone.gov.np/media/pdf_upload/01%20Executive%20Summary%20Project%20on%20Integrated%20Power%20System%20Development%20Plan%20in%20Nepal%202025.06.09_g8l5n0c.pdf",
        "source_type": "pdf",
        "document_class": "master_plan_summary",
        "primary_use": "reference_only",
        "note": "Useful for current and future interconnection framing, not detailed route tracing.",
    },
    {
        "source_id": "adb_sasec_operational_plan_update",
        "title": "ADB SASEC Operational Plan 2016-2025 Update",
        "path": RAW / "corridor_tracing" / "adb_sasec_operational_plan_update.pdf",
        "url": "https://www.adb.org/sites/default/files/institutional-document/551061/sasec-operational-plan-2016-2025-update.pdf",
        "source_type": "pdf",
        "document_class": "regional_plan",
        "primary_use": "planning_reference",
        "note": "Useful for corridor grouping and MCA project framing, not exact tracing.",
    },
    {
        "source_id": "jica_ipsdp_report_part2",
        "title": "JICA IPSDP Report Part 2",
        "path": RAW / "corridor_tracing" / "jica" / "jica_ipsdp_report_part2.pdf",
        "url": "https://openjicareport.jica.go.jp/pdf/12387999_02.pdf",
        "source_type": "pdf",
        "document_class": "master_plan_report",
        "primary_use": "basin_grouping_reference",
        "note": "Good for corridor family grouping and planning context, not exact routing.",
    },
    {
        "source_id": "nea_annual_report_2024_2025",
        "title": "NEA Annual Report FY 2024/25",
        "path": RAW / "projects_storage" / "nea_annual_report_2024_2025.pdf",
        "url": "",
        "source_type": "pdf",
        "document_class": "annual_report",
        "primary_use": "status_reference",
        "note": "Best local source for current operational and under-construction line lists; not a route atlas.",
    },
    {
        "source_id": "nea_transmission_annual_book_2077",
        "title": "NEA Transmission Annual Book 2077 (FY 2019/20)",
        "path": RAW / "corridor_tracing" / "nea" / "nea_transmission_annual_book_2077.pdf",
        "url": "https://neasite.dryicesolutions.net/uploads/shares/annual_report/Annual_book_2077.pdf",
        "source_type": "pdf",
        "document_class": "annual_book",
        "primary_use": "manual_route_basis",
        "note": "Recovered from the live NEA dryicesolutions mirror on 2026-04-18. Useful for Solu corridor narrative evidence, especially the Tingla substation page and the Maruwa rerouting note.",
    },
    {
        "source_id": "nea_bharatpur_bardaghat_sia",
        "title": "NEA Bharatpur-Bardaghat 220 kV Transmission Line SIA",
        "path": RAW / "corridor_tracing" / "nea" / "nea_bharatpur_bardaghat_sia.pdf",
        "url": "https://www.nea.org.np/admin/assets/uploads/supportive_docs/SIA-Bharatpur-Bardghat.pdf",
        "source_type": "pdf",
        "document_class": "environmental_study",
        "primary_use": "manual_route_basis",
        "note": "Official NEA SIA source identified during the HBB repair pass. The live NEA file endpoint rejected direct download in this environment, but the indexed text states the Bharatpur-Bardaghat alignment, affected VDC corridor, and 73.5 km route length.",
    },
    {
        "source_id": "nea_marsyangdi_rap",
        "title": "NEA Marsyangdi Corridor RAP / route packet",
        "path": RAW / "corridor_tracing" / "nea" / "nea_marsyangdi_rap.pdf",
        "url": "https://neasite.dryicesolutions.net/uploads/shares/publication/17560727.pdf",
        "source_type": "pdf",
        "document_class": "rap",
        "primary_use": "trace_grade",
        "note": "Recovered from the live NEA dryicesolutions mirror on 2026-04-18. This is the main route-grade packet for Udipur-Markichowk-Bharatpur.",
    },
    {
        "source_id": "nea_kabeli_iee",
        "title": "NEA Kabeli Corridor IEE",
        "path": RAW / "corridor_tracing" / "nea" / "nea_kabeli_iee.pdf",
        "url": "https://web.archive.org/web/20120216232653/http://www.nea.org.np/images/supportive_docs/Initial%20Environmental%20Examination%20_IEE_%20Study%20Vol-I%20of%20Kabeli%20Corridor%20TL%20Project.pdf",
        "source_type": "pdf",
        "document_class": "iee",
        "primary_use": "trace_grade",
        "note": "Recovered from Wayback on 2026-04-18 using the original NEA /images/supportive_docs path. This is now the primary route-grade source for the Kabeli corridor family.",
    },
    {
        "source_id": "nea_kabeli_smef",
        "title": "NEA Kabeli Corridor SMEF",
        "path": RAW / "corridor_tracing" / "nea" / "nea_kabeli_smef.pdf",
        "url": "https://web.archive.org/web/20120216232653/http://www.nea.org.np/images/supportive_docs/SOCIAL%20MANAGEMENT%20and%20ENTITLEMENT%20FRAMEWORK%20-%20Kabeli%20TL.pdf",
        "source_type": "pdf",
        "document_class": "smef",
        "primary_use": "supporting_alignment_context",
        "note": "Recovered from Wayback on 2026-04-18. Useful for project description, location, substation references, and impact-area framing around the Kabeli line.",
    },
    {
        "source_id": "nea_marsyangdi_rap_upper",
        "title": "NEA Marsyangdi Corridor RAP (Manang-Khudi-Udipur)",
        "path": RAW / "corridor_tracing" / "nea" / "nea_marsyangdi_rap_upper.pdf",
        "url": "https://neasite.dryicesolutions.net/uploads/shares/publication/52182611.pdf",
        "source_type": "pdf",
        "document_class": "rap",
        "primary_use": "trace_grade",
        "note": "Recovered from the live NEA dryicesolutions mirror on 2026-04-18. Companion route-grade source for the upper Marsyangdi section.",
    },
    {
        "source_id": "eib_marsyangdi_cia",
        "title": "EIB Marsyangdi Corridor CIA",
        "path": RAW / "corridor_tracing" / "nea" / "eib_marsyangdi_cia.pdf",
        "url": "https://www.eib.org/attachments/registers/168770873.pdf",
        "source_type": "pdf",
        "document_class": "cia",
        "primary_use": "supporting_alignment_context",
        "note": "Companion source recovered on 2026-04-18. Useful for updated corridor context, cumulative impact framing, and segment lengths.",
    },
]


MANIFEST_ROWS: list[dict[str, Any]] = [
    {
        "corridor_id": "hddi_400",
        "segment_id": "hetauda_dhalkebar_inaruwa",
        "segment_name": "Hetauda-Dhalkebar-Inaruwa 400 kV backbone",
        "source_id": "world_bank_hddtl_rap",
        "priority": "high",
        "page_start": 16,
        "page_end": 16,
        "figure_or_sheet": "candidate route-map page",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Hetauda",
        "endpoint_b": "Duhabi / Inaruwa",
        "official_length_km": 285.2,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "World Bank RAP is the main public route-map source for HDDTL. Candidate map page confirmed as image-heavy and trace-worthy; exact figure caption still needs page-image review.",
    },
    {
        "corridor_id": "hddi_400",
        "segment_id": "hetauda_dhalkebar_inaruwa",
        "segment_name": "Hetauda-Dhalkebar-Inaruwa 400 kV backbone",
        "source_id": "world_bank_hddtl_rap",
        "priority": "high",
        "page_start": 2,
        "page_end": 2,
        "figure_or_sheet": "executive summary corridor description",
        "source_role": "reference_only",
        "endpoint_a": "Hetauda",
        "endpoint_b": "Duhabi / Inaruwa",
        "official_length_km": 285.2,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Text summary explicitly states start, end, districts crossed, and total alignment length.",
    },
    {
        "corridor_id": "hddi_400",
        "segment_id": "hetauda_dhalkebar_inaruwa",
        "segment_name": "Hetauda-Dhalkebar-Inaruwa 400 kV backbone",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 176,
        "page_end": 176,
        "figure_or_sheet": "under-construction line table",
        "source_role": "status_reference",
        "endpoint_a": "Hetauda",
        "endpoint_b": "Dhalkebar",
        "official_length_km": 270.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Useful for current project status and NEA naming, not precise route tracing.",
    },
    {
        "corridor_id": "hetauda_bharatpur_bardaghat_220",
        "segment_id": "hetauda_new_bharatpur",
        "segment_name": "Hetauda-New Bharatpur 220 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing/under-construction 220 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Hetauda",
        "endpoint_b": "New Bharatpur",
        "official_length_km": 73.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Manual selection of the official-vector Hetauda-New Bharatpur line from the RPGCL geospatial PDF, cross-checked against NEA/current public status references that state about 73 route-km.",
    },
    {
        "corridor_id": "hetauda_bharatpur_bardaghat_220",
        "segment_id": "new_bharatpur_bardaghat",
        "segment_name": "New Bharatpur-Bardaghat 220 kV line",
        "source_id": "nea_bharatpur_bardaghat_sia",
        "priority": "high",
        "page_start": 1,
        "page_end": 7,
        "figure_or_sheet": "chapter 1 route length and chapter 3 project-area VDC list",
        "source_role": "manual_route_basis",
        "endpoint_a": "New Bharatpur / Aaptari",
        "endpoint_b": "Bardaghat",
        "official_length_km": 73.5,
        "geometry_confidence": "medium",
        "status": "confirmed_web_source",
        "notes": "Official NEA SIA establishes the Bharatpur-Bardaghat route length as 73.5 km and lists the affected Bharatpur/Nawalparasi corridor. Used as a source-bounded manual corridor trace, not tower-level alignment.",
    },
    {
        "corridor_id": "hetauda_bharatpur_bardaghat_220",
        "segment_id": "hetauda_bharatpur_bardaghat_status",
        "segment_name": "Hetauda-Bharatpur-Bardaghat 220 kV corridor status",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 42,
        "page_end": 42,
        "figure_or_sheet": "NIETTP status text",
        "source_role": "status_reference",
        "endpoint_a": "Hetauda",
        "endpoint_b": "Bardaghat",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms completion under World Bank additional funding, but no route map on this page.",
    },
    {
        "corridor_id": "dana_kushma_butwal_220",
        "segment_id": "dana_kushma",
        "segment_name": "Dana-Kushma 220 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing/under-construction 220 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Dana",
        "endpoint_b": "Kushma",
        "official_length_km": 39.57,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route selected from the RPGCL geospatial PDF and controlled against NEA Transmission Annual Book 2077 route length.",
    },
    {
        "corridor_id": "dana_kushma_butwal_220",
        "segment_id": "kushma_new_butwal",
        "segment_name": "Kushma-New Butwal 220 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing/under-construction 220 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Kushma",
        "endpoint_b": "New Butwal",
        "official_length_km": 88.0,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route selected from the RPGCL geospatial PDF and controlled against NEA Transmission Annual Book 2077 route length.",
    },
    {
        "corridor_id": "dana_kushma_butwal_220",
        "segment_id": "dana_kushma_butwal_status",
        "segment_name": "Dana-Kushma-New Butwal 220 kV corridor status",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 69,
        "page_end": 70,
        "figure_or_sheet": "PMD completed-project text and FY2024/25 existing 220 kV inventory",
        "source_role": "status_reference",
        "endpoint_a": "Dana / Kushma",
        "endpoint_b": "New Butwal",
        "official_length_km": 127.57,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Confirms the corridor is operational: New Butwal became fully operational after Kushma-New Butwal was finished; the existing-line inventory lists Dana-Kushma and Kushma-New Butwal as double-circuit 220 kV lines.",
    },
    {
        "corridor_id": "dana_kushma_butwal_220",
        "segment_id": "dana_kushma_butwal_length",
        "segment_name": "Dana-Kushma-New Butwal 220 kV route length",
        "source_id": "nea_transmission_annual_book_2077",
        "priority": "high",
        "page_start": 146,
        "page_end": 147,
        "figure_or_sheet": "Kaligandaki Corridor 220 kV project text",
        "source_role": "manual_route_basis",
        "endpoint_a": "Dana",
        "endpoint_b": "New Butwal",
        "official_length_km": 127.57,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "States 127.57 km for Dana-Kushma-New Butwal, with 39.57 km for Dana-Kushma and 88 km for Kushma-New Butwal.",
    },
    {
        "corridor_id": "western_132_backbone",
        "segment_id": "butwal_shivapur_lamahi_kohalpur",
        "segment_name": "Butwal-Shivapur-Lamahi-Kohalpur 132 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing 132 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Butwal",
        "endpoint_b": "Kohalpur",
        "official_length_km": 215.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route reconstructed from RPGCL drawing strokes and controlled by NEA FY2024/25 existing-line inventory, which lists this double-circuit 132 kV line as 430 circuit-km.",
    },
    {
        "corridor_id": "chameliya_attariya_132",
        "segment_id": "kohalpur_bhurigaun_lamki",
        "segment_name": "Kohalpur-Bhurigaun-Lamki 132 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing 132 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Kohalpur",
        "endpoint_b": "Lamki",
        "official_length_km": 88.33,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route reconstructed from RPGCL drawing strokes and controlled by NEA FY2024/25 existing-line inventory, which lists this double-circuit 132 kV line as 176.66 circuit-km.",
    },
    {
        "corridor_id": "western_132_backbone",
        "segment_id": "lamki_pahalwanpur_attariya_mahendranagar",
        "segment_name": "Lamki-Pahalwanpur-Attariya-Mahendranagar 132 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing 132 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Lamki",
        "endpoint_b": "Mahendranagar",
        "official_length_km": 101.56,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route reconstructed from RPGCL drawing strokes and controlled by NEA FY2024/25 existing-line inventory, which lists this double-circuit 132 kV line as 203.12 circuit-km.",
    },
    {
        "corridor_id": "western_132_backbone",
        "segment_id": "chameliya_syaule_attariya",
        "segment_name": "Chameliya-Syaule-Attariya 132 kV line",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "high",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "existing 132 kV geospatial linework",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Chameliya",
        "endpoint_b": "Attariya",
        "official_length_km": 131.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Official-vector route reconstructed from RPGCL drawing strokes and controlled by NEA FY2024/25 existing-line inventory, which lists this double-circuit 132 kV line as 262 circuit-km.",
    },
    {
        "corridor_id": "western_132_backbone",
        "segment_id": "western_132_existing_inventory",
        "segment_name": "Western Nepal operational 132 kV backbone inventory",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "high",
        "page_start": 172,
        "page_end": 173,
        "figure_or_sheet": "existing high-voltage transmission line inventory",
        "source_role": "status_reference",
        "endpoint_a": "Butwal",
        "endpoint_b": "Mahendranagar",
        "official_length_km": 404.89,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms the operational Butwal-Kohalpur-Lamki-Attariya-Mahendranagar 132 kV Terai backbone line names and circuit-km values used to control route length.",
    },
    {
        "corridor_id": "chameliya_attariya_132",
        "segment_id": "western_132_existing_inventory",
        "segment_name": "Western Nepal operational 132 kV backbone inventory",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "high",
        "page_start": 172,
        "page_end": 173,
        "figure_or_sheet": "existing high-voltage transmission line inventory",
        "source_role": "status_reference",
        "endpoint_a": "Chameliya",
        "endpoint_b": "Attariya",
        "official_length_km": 131.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms Chameliya-Syaule-Attariya as an operational double-circuit 132 kV line with 262 circuit-km, equivalent to about 131 route-km.",
    },
    {
        "corridor_id": "kohalpur_surkhet_dailekh_132",
        "segment_id": "kohalpur_surkhet_dailekh",
        "segment_name": "Kohalpur-Surkhet-Dailekh 132 kV grid anchor labels",
        "source_id": "rpgcl_transmission_network_map_revised1",
        "priority": "medium",
        "page_start": 1,
        "page_end": 1,
        "figure_or_sheet": "Kohalpur, Surkhet, and Dailekh map labels",
        "source_role": "supporting_alignment_context",
        "endpoint_a": "Kohalpur",
        "endpoint_b": "Dailekh",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Used for route anchor placement only. NEA FY2024/25 controls status and length for the under-construction line.",
    },
    {
        "corridor_id": "kohalpur_surkhet_dailekh_132",
        "segment_id": "kohalpur_surkhet_dailekh",
        "segment_name": "Kohalpur-Surkhet-Dailekh 132 kV line",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "high",
        "page_start": 35,
        "page_end": 35,
        "figure_or_sheet": "project status narrative",
        "source_role": "manual_route_basis",
        "endpoint_a": "Kohalpur",
        "endpoint_b": "Dailekh",
        "official_length_km": 84.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "NEA FY2024/25 states the project builds 52 km from Kohalpur to Surkhet and 32 km from Surkhet to Dailekh, with significant construction progress by July 2025.",
    },
    {
        "corridor_id": "kohalpur_surkhet_dailekh_132",
        "segment_id": "kohalpur_surkhet_dailekh_inventory",
        "segment_name": "Kohalpur-Surkhet-Dailekh 132 kV line inventory",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 175,
        "page_end": 175,
        "figure_or_sheet": "under-construction line table",
        "source_role": "status_reference",
        "endpoint_a": "Kohalpur",
        "endpoint_b": "Dailekh",
        "official_length_km": 84.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Under-construction table lists the double-circuit package as 168 circuit-km with a 2026/27 target.",
    },
    {
        "corridor_id": "mca_central_400",
        "segment_id": "lapsiphedi_ratmate_hetauda_damauli_butwal",
        "segment_name": "Lapsiphedi-Ratmate-Hetauda-Damauli-Butwal 400 kV central corridor",
        "source_id": "mca_annex_d1_alignment_maps",
        "priority": "high",
        "page_start": 1,
        "page_end": 193,
        "figure_or_sheet": "alignment atlas, sheet range pending exact selection",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Lapsiphedi",
        "endpoint_b": "Butwal",
        "official_length_km": "",
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Best route-grade source for the MCA corridor. Exact corridor sheet numbers still need OCR or manual sheet-title identification.",
    },
    {
        "corridor_id": "mca_central_400",
        "segment_id": "lapsiphedi_ratmate_hetauda_damauli_butwal",
        "segment_name": "Lapsiphedi-Ratmate-Hetauda-Damauli-Butwal 400 kV central corridor",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 175,
        "page_end": 176,
        "figure_or_sheet": "under-construction line tables",
        "source_role": "status_reference",
        "endpoint_a": "Ratmate",
        "endpoint_b": "Butwal",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms Galchhi-Ratmate and Lapang-Ratmate in NEA tables, but the main MCA corridor still requires the alignment atlas.",
    },
    {
        "corridor_id": "mca_central_400",
        "segment_id": "lapsiphedi_ratmate_hetauda_damauli_butwal",
        "segment_name": "Lapsiphedi-Ratmate-Hetauda-Damauli-Butwal 400 kV central corridor",
        "source_id": "mca_project_summary_report",
        "priority": "medium",
        "page_start": "",
        "page_end": "",
        "figure_or_sheet": "older Naubise-based planning nomenclature",
        "source_role": "naming_reference",
        "endpoint_a": "Lapsiphedi / Naubise",
        "endpoint_b": "Butwal",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Use for naming reconciliation only. This document reflects the earlier Naubise-centered planning vocabulary rather than the current Ratmate-centered MCA hub naming.",
    },
    {
        "corridor_id": "udipur_damauli_bharatpur_220",
        "segment_id": "udipur_markichowk_bharatpur",
        "segment_name": "Udipur-Markichowk-Bharatpur 220 kV corridor",
        "source_id": "nea_marsyangdi_rap",
        "priority": "high",
        "page_start": 22,
        "page_end": 23,
        "figure_or_sheet": "Project description and project location map",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Udipur",
        "endpoint_b": "Bharatpur",
        "official_length_km": "",
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Primary route-grade source recovered from the live NEA dryicesolutions mirror. Page 23 contains the main project location map with Udipur, Markichowk, and New Bharatpur substations labeled.",
    },
    {
        "corridor_id": "udipur_damauli_bharatpur_220",
        "segment_id": "udipur_markichowk_bharatpur",
        "segment_name": "Udipur-Markichowk-Bharatpur 220 kV corridor",
        "source_id": "eib_marsyangdi_cia",
        "priority": "medium",
        "page_start": 45,
        "page_end": 47,
        "figure_or_sheet": "CIA study area and landuse maps",
        "source_role": "supporting_alignment_context",
        "endpoint_a": "Dharapani / Khudi / Udipur context",
        "endpoint_b": "Markichowk / Bharatpur context",
        "official_length_km": 112.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Companion context source. Page 45 shows the CIA study-area location map, and page 47 shows a corridor-wide landuse map with major Marsyangdi substations labeled.",
    },
    {
        "corridor_id": "udipur_damauli_bharatpur_220",
        "segment_id": "udipur_markichowk_bharatpur",
        "segment_name": "Udipur-Markichowk-Bharatpur 220 kV corridor",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 176,
        "page_end": 176,
        "figure_or_sheet": "under-construction line table",
        "source_role": "status_reference",
        "endpoint_a": "Udipur",
        "endpoint_b": "Bharatpur",
        "official_length_km": 134.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Useful for project status and official segment names Khudi-Udipur and Udipur-Bharatpur.",
    },
    {
        "corridor_id": "kabeli_132",
        "segment_id": "godak_soyak_amarpur",
        "segment_name": "Kabeli / Godak-Soyak-Amarpur 132 kV corridor",
        "source_id": "nea_kabeli_iee",
        "priority": "high",
        "page_start": 25,
        "page_end": 27,
        "figure_or_sheet": "Figure 2.1-2.3 location, district/VDC, and alignment-summary pages",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Godak",
        "endpoint_b": "Amarpur",
        "official_length_km": 83.74,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Primary route-grade source for the Kabeli corridor family, recovered from Wayback using the original NEA supportive_docs path. Page 25 shows the national location map, page 26 shows the district/VDC corridor map, and page 27 gives the alignment narrative and references Figure 2.3 sheets 1 to 15.",
    },
    {
        "corridor_id": "kabeli_132",
        "segment_id": "godak_soyak_amarpur",
        "segment_name": "Kabeli / Godak-Soyak-Amarpur 132 kV corridor",
        "source_id": "nea_kabeli_smef",
        "priority": "medium",
        "page_start": 8,
        "page_end": 9,
        "figure_or_sheet": "SMEF project location maps",
        "source_role": "supporting_alignment_context",
        "endpoint_a": "Lakhanpur / Damak context",
        "endpoint_b": "Phidim / Kabeli context",
        "official_length_km": 83.74,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Supporting context source. The SMEF contains an additional project location map and social-impact framing around the Kabeli alignment.",
    },
    {
        "corridor_id": "marsyangdi_upper_220",
        "segment_id": "manang_khudi_udipur",
        "segment_name": "Marsyangdi Corridor Manang-Khudi-Udipur 220 kV",
        "source_id": "nea_marsyangdi_rap_upper",
        "priority": "high",
        "page_start": 33,
        "page_end": 36,
        "figure_or_sheet": "Project location, district, project-area, and accessibility maps",
        "source_role": "trace_grade_candidate",
        "endpoint_a": "Dharapani / Manang",
        "endpoint_b": "Khudi / Udipur",
        "official_length_km": 46.0,
        "geometry_confidence": "high",
        "status": "confirmed_doc_local",
        "notes": "Recovered companion route-grade source for the upper Marsyangdi section. Page 33 has the national location map, page 34 has district and project-area maps, and page 36 has the accessibility map.",
    },
    {
        "corridor_id": "kabeli_132",
        "segment_id": "godak_soyak_amarpur",
        "segment_name": "Kabeli / Godak-Soyak-Amarpur 132 kV corridor",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 175,
        "page_end": 175,
        "figure_or_sheet": "under-construction line table",
        "source_role": "status_reference",
        "endpoint_a": "Amarpur",
        "endpoint_b": "Dhungesangu / Soyak",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms the Kabeli (Amarpur)-Dhungesangu and Godak-Soyak packages in current NEA nomenclature.",
    },
    {
        "corridor_id": "solu_tingla_mirchaiya_132",
        "segment_id": "tingla_mirchaiya",
        "segment_name": "Solu Corridor Tingla-Mirchaiya 132 kV",
        "source_id": "nea_annual_report_2024_2025",
        "priority": "medium",
        "page_start": 173,
        "page_end": 174,
        "figure_or_sheet": "existing high-voltage line inventory",
        "source_role": "status_reference",
        "endpoint_a": "Tingla",
        "endpoint_b": "Mirchaiya",
        "official_length_km": 180.0,
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Confirms current line presence and nominal length; still needs a route-grade NEA corridor packet for accurate tracing.",
    },
    {
        "corridor_id": "solu_tingla_mirchaiya_132",
        "segment_id": "tingla_mirchaiya",
        "segment_name": "Solu Corridor Tingla-Mirchaiya 132 kV",
        "source_id": "nea_transmission_annual_book_2077",
        "priority": "high",
        "page_start": 47,
        "page_end": 52,
        "figure_or_sheet": "Tingla substation and Solu Corridor project narrative pages",
        "source_role": "manual_route_basis",
        "endpoint_a": "Mirchaiya",
        "endpoint_b": "Tingla",
        "official_length_km": 90.0,
        "geometry_confidence": "low",
        "status": "confirmed_doc_local",
        "notes": "Page 47 confirms the Mirchaiya-Tingla 132 kV double-circuit line as a 90 km corridor feeding the Solu basin into Tingla. Page 52 confirms the same project scope and records the rerouting dispute at Maruwa in Katari municipality, which is the key mid-corridor anchor for the current manual trace.",
    },
    {
        "corridor_id": "future_interconnections",
        "segment_id": "butwal_gorakhpur_inaruwa_purnea_lamki_bareilly",
        "segment_name": "Future export interconnection package",
        "source_id": "moewri_ipsdp_exec_summary_2025",
        "priority": "medium",
        "page_start": 24,
        "page_end": 24,
        "figure_or_sheet": "Table 2.4-4 future interconnection lines",
        "source_role": "planning_reference",
        "endpoint_a": "",
        "endpoint_b": "",
        "official_length_km": "",
        "geometry_confidence": "medium",
        "status": "confirmed_doc_local",
        "notes": "Planning reference for future interconnections and associated domestic 400 kV grids; not route-grade geometry.",
    },
]


def source_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source in SOURCES:
        path = source["path"]
        exists_local = False
        if path.exists() and path.is_file():
            try:
                with path.open("rb") as handle:
                    header = handle.read(4)
                exists_local = path.stat().st_size > 1024 and header == b"%PDF"
            except OSError:
                exists_local = False
        rows.append(
            {
                "source_id": source["source_id"],
                "title": source["title"],
                "path": str(path),
                "exists_local": exists_local,
                "url": source["url"],
                "source_type": source["source_type"],
                "document_class": source["document_class"],
                "primary_use": source["primary_use"],
                "note": source["note"],
            }
        )
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    PROCESSED.mkdir(parents=True, exist_ok=True)

    sources = source_rows()
    manifest = []
    for row in MANIFEST_ROWS:
        source = next(item for item in sources if item["source_id"] == row["source_id"])
        manifest.append(row | {"source_path": source["path"], "source_exists_local": source["exists_local"]})

    write_csv(PROCESSED / "corridor_source_inventory.csv", sources)
    write_csv(PROCESSED / "corridor_trace_manifest.csv", manifest)
    (PROCESSED / "corridor_source_inventory.json").write_text(json.dumps(sources, indent=2))
    (PROCESSED / "corridor_trace_manifest.json").write_text(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
