#!/usr/bin/env python3
"""Second cleanup pass: drop frontmatter `images:` filmstrip entries with
junk captions (boilerplate autogenerated captions that provide zero signal).

Drops:
  - "NEA annual-book image from page N."
  - "PDF image from page N."
  - "Source: X" (bare source line captured instead of a real caption)
  - "Annex N;..."
  - "[no caption]"

Also prunes:
  - the matching asset file
  - its provenance entry
  - the source slug from frontmatter `sources:` if no other asset from that
    source remains on the page
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pdf_atlas_lib import ASSETS_DIR, SOURCES  # noqa: E402
from extract_pdf_images import (  # noqa: E402
    remove_frontmatter_image,
    remove_provenance_entry,
    remove_source_slug_if_unused,
)


PREFIX_TO_SOURCE: dict[str, dict[str, str]] = {
    source["asset_prefix"]: {"slug": source["wiki_source_slug"], "prov": source["provenance_filename"]}
    for source in SOURCES.values()
}


BOILERPLATE_CAPTION_PREFIXES = (
    "nea annual-book image from page",
    "pdf image from page",
    "source:",
    "annex ",
)


def is_junk(caption: str) -> bool:
    c = (caption or "").strip().lower()
    if not c or c == "[no caption]":
        return True
    for prefix in BOILERPLATE_CAPTION_PREFIXES:
        if c.startswith(prefix):
            return True
    return False


def asset_prefix_from_src(src: str) -> str | None:
    match = re.match(r"([a-z0-9]+)-p\d", Path(src).name)
    return match.group(1) if match else None


FRONTMATTER_IMAGE_BLOCK_RE = re.compile(
    r"^\s{2}- src:\s*(\S+)\n(?:^\s{4}.*\n)+",
    re.MULTILINE,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    dropped = 0
    assets_removed = 0
    pages_touched = 0

    for page_path in sorted(Path("wiki/pages").glob("*/*.md")):
        text = page_path.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            continue
        fm_end = text.find("\n---\n", 4)
        if fm_end < 0:
            continue
        fm = text[4:fm_end]

        to_drop: list[str] = []
        for match in FRONTMATTER_IMAGE_BLOCK_RE.finditer(fm):
            block = match.group(0)
            cap_m = re.search(r"caption:\s*\"?([^\"\n]+)\"?", block)
            if cap_m and is_junk(cap_m.group(1)):
                to_drop.append(match.group(1))

        if not to_drop:
            continue

        new_text = text
        for src in to_drop:
            new_text = remove_frontmatter_image(new_text, src)
            prefix = asset_prefix_from_src(src) or ""
            meta = PREFIX_TO_SOURCE.get(prefix)
            prov_slug = src.split("/", 1)[0]
            if meta:
                new_text = remove_source_slug_if_unused(new_text, meta["slug"], prefix)
                prov_path = ASSETS_DIR / prov_slug / meta["prov"]
                if prov_path.exists():
                    try:
                        prov_data = json.loads(prov_path.read_text(encoding="utf-8"))
                    except json.JSONDecodeError:
                        prov_data = None
                    if prov_data:
                        updated_prov = remove_provenance_entry(prov_data, src, prov_slug)
                        if updated_prov is None:
                            if not args.dry_run:
                                prov_path.unlink()
                        else:
                            if not args.dry_run:
                                prov_path.write_text(
                                    json.dumps(updated_prov, indent=2, ensure_ascii=False) + "\n",
                                    encoding="utf-8",
                                )
            dropped += 1
            asset_abs = ASSETS_DIR / src
            if asset_abs.exists():
                if not args.dry_run:
                    asset_abs.unlink()
                    parent = asset_abs.parent
                    if parent.exists() and not any(parent.iterdir()):
                        parent.rmdir()
                assets_removed += 1
            print(f"  drop: {page_path.relative_to('wiki/pages')}: {src}")

        if new_text != text:
            pages_touched += 1
            if not args.dry_run:
                page_path.write_text(new_text, encoding="utf-8")

    print()
    print(f"pages_touched={pages_touched}")
    print(f"frontmatter_image_entries_dropped={dropped}")
    print(f"assets_removed={assets_removed}")


if __name__ == "__main__":
    main()
