#!/usr/bin/env python3
"""Generate wiki stub pages for curated map features that don't have one yet,
and sync bindings.json so every stub is reachable from the map.

Target tier (Tier 2 = Tier 1 + operating/construction/survey above capacity floor):
  - priority_watchlist      (all 12)
  - storage_shortlist       (all 11)
  - top_capacity            (all 10)
  - hydropower_operating    capacity_mw >= 20
  - hydropower_construction capacity_mw >= 20
  - hydropower_survey       capacity_mw >= 200

Deduping rules:
  1. Slugs are derived from the same JS rule the explorer uses:
     name.toLowerCase().replace(/[^a-z0-9]+/g, '-').strip('-')
     so map-popup slugs and filesystem slugs match.
  2. A hand-maintained SLUG_ALIASES map folds registry name variants into the
     canonical existing page (e.g. 'upper-tamakoshi-hpp' -> 'upper-tamakoshi').
  3. Stubs are never overwritten. A stub is a file whose frontmatter contains
     `generator: auto-stub`; its autogenerated spec table lives between
     `<!-- generated:specs:start -->` and `<!-- generated:specs:end -->`
     markers, so it can be refreshed with --refresh-specs without touching prose.

Outputs:
  - wiki/pages/entities/<slug>.md           (new stubs)
  - wiki/explorer/shared/bindings.json      (new feature bindings, idempotent)

Run:
  python3 scripts/gen_wiki_stubs.py                 # dry-run (default, no writes)
  python3 scripts/gen_wiki_stubs.py --write         # create stubs + update bindings
  python3 scripts/gen_wiki_stubs.py --refresh-specs # also refresh spec tables in existing auto-stubs
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "wiki" / "explorer" / "shared"
MANIFEST = SHARED / "layer-manifest.json"
BINDINGS = SHARED / "bindings.json"
SLUG_ALIASES_PATH = SHARED / "hydropower-slug-aliases.json"
PAGES = ROOT / "wiki" / "pages"
ENTITIES = PAGES / "entities"

# --------------------------------------------------------------------------- #
#  Tier definitions                                                            #
# --------------------------------------------------------------------------- #
TARGETS: list[tuple[str, int, float | None]] = [
    # (layer_key, rank, min_capacity_mw)
    # Lower rank = more canonical; used to pick primary binding + merge props.
    ("priority_watchlist",      0, None),
    ("storage_shortlist",       1, None),
    ("top_capacity",            2, None),
    ("hydropower_operating",   10, 20.0),
    ("hydropower_construction", 11, 20.0),
    ("hydropower_survey",      12, 200.0),
]

# Existing pages that different MoE registry names collide with.
# Key = slug that this generator would create; value = canonical existing slug.
SLUG_ALIASES: dict[str, str] = json.loads(SLUG_ALIASES_PATH.read_text(encoding="utf-8"))

# River-name -> canonical basin slug, best-effort.
# Entries are substring matches, evaluated in order.
BASIN_BY_RIVER: list[tuple[str, str]] = [
    ("tama koshi",   "koshi-basin"),
    ("tamakoshi",    "koshi-basin"),
    ("dudh koshi",   "koshi-basin"),
    ("dudhkoshi",    "koshi-basin"),
    ("sun koshi",    "koshi-basin"),
    ("sunkoshi",     "koshi-basin"),
    ("bhote koshi",  "koshi-basin"),
    ("bhotekoshi",   "koshi-basin"),
    ("balephi",      "koshi-basin"),
    ("indravati",    "koshi-basin"),
    ("indrawati",    "koshi-basin"),
    ("likhu",        "koshi-basin"),
    ("arun",         "koshi-basin"),
    ("tamor",        "koshi-basin"),
    ("milke",        "koshi-basin"),
    ("koshi",        "koshi-basin"),

    ("kali gandaki", "gandaki-basin"),
    ("kaligandaki",  "gandaki-basin"),
    ("marsyangdi",   "gandaki-basin"),
    ("budhi gandaki","gandaki-basin"),
    ("budhigandaki", "gandaki-basin"),
    ("trishuli",     "gandaki-basin"),
    ("seti ",        "gandaki-basin"),
    ("madi",         "gandaki-basin"),
    ("daraudi",      "gandaki-basin"),
    ("andhi khola",  "gandaki-basin"),
    ("modi khola",   "gandaki-basin"),
    ("narayani",     "gandaki-basin"),
    ("gandaki",      "gandaki-basin"),

    ("humla karnali","karnali-basin"),
    ("mugu karnali", "karnali-basin"),
    ("tila",         "karnali-basin"),
    ("bheri",        "karnali-basin"),
    ("phukot",       "karnali-basin"),
    ("west rapti",   "karnali-basin"),
    ("w. rapti",     "karnali-basin"),
    ("rapti",        "karnali-basin"),
    ("chainpur seti","karnali-basin"),
    ("seti",         "karnali-basin"),
    ("karnali",      "karnali-basin"),

    ("chamliya",     "mahakali-basin"),
    ("chameliya",    "mahakali-basin"),
    ("mahakali",     "mahakali-basin"),
]

SPEC_START = "<!-- generated:specs:start -->"
SPEC_END = "<!-- generated:specs:end -->"
SPECS_CSV = ROOT / "data" / "project_specs.csv"

# Section → [(csv_column, display_label, suffix), ...]
# Grouped by the user's chosen sections: Engineering / Output / Financial / Governance / Schedule.
# Storage fields are a sub-section of Engineering (dam/reservoir specs).
# Only sections with at least one non-empty value are rendered.
SPEC_SECTIONS: list[tuple[str, list[tuple[str, str, str]]]] = [
    ("Engineering", [
        ("gross_head_m",            "Gross head",               " m"),
        ("design_discharge_m3s",    "Design discharge",         " m³/s"),
        ("headrace_tunnel_km",      "Headrace tunnel",          " km"),
        ("dam_height_m",            "Dam height",               " m"),
        ("dam_type",                "Dam type",                 ""),
        ("num_units",               "Units",                    ""),
        ("unit_capacity_mw",        "Unit capacity",            " MW"),
        ("turbine_type",            "Turbine type",             ""),
        ("underground_powerhouse",  "Underground powerhouse",   ""),
        ("penstock_length_m",       "Penstock length",          " m"),
        ("penstock_diameter_m",     "Penstock diameter",        " m"),
        ("tailrace_length_m",       "Tailrace length",          " m"),
    ]),
    ("Storage", [
        ("total_storage_mcm",       "Total storage",            " MCM"),
        ("effective_storage_mcm",   "Effective storage",        " MCM"),
        ("pumped_storage_mw",       "Pumped storage component", " MW"),
    ]),
    ("Output", [
        ("annual_design_energy_gwh","Annual design energy",     " GWh"),
        ("dry_season_energy_gwh",   "Dry-season energy",        " GWh"),
        ("dry_share_pct",           "Dry-season share",         " %"),
        ("plant_load_factor_pct",   "Plant load factor",        " %"),
        ("q_design",                "Q-design",                 ""),
        ("project_type",            "Type",                     ""),
        ("catchment_area_km2",      "Catchment area",           " km²"),
        ("environmental_release_m3s","Environmental release",   " m³/s"),
    ]),
    ("Financial", [
        ("total_cost_usd_m",        "Total cost",               " million USD"),
        ("cost_per_mw_usd_m",       "Cost per MW",              " million USD/MW"),
        ("ppa_rate_wet_npr_kwh",    "PPA rate (wet)",           " NPR/kWh"),
        ("ppa_rate_dry_npr_kwh",    "PPA rate (dry)",           " NPR/kWh"),
        ("debt_equity_ratio",       "Debt/equity",              ""),
    ]),
    ("Governance", [
        ("developer",               "Developer",                ""),
        ("concession_type",         "Concession type",          ""),
        ("lead_financier",          "Lead financier",           ""),
        ("concession_years",        "Concession period",        " years"),
    ]),
    ("Schedule", [
        ("construction_start_year", "Construction start",       ""),
        ("cod_year",                "Commercial operation",     ""),
        ("completion_pct",          "Completion",               " %"),
    ]),
]


# --------------------------------------------------------------------------- #
#  Helpers                                                                     #
# --------------------------------------------------------------------------- #
# Common suffixes that bloat slug names when they come from verbose registry
# project titles. Stripped BEFORE slugification so that "Super Nyadi
# Hydropower Project" → "super-nyadi" rather than "super-nyadi-hydropower-project".
PROJECT_SUFFIXES = [
    " Hydropower Project", " Hydroelectric Project", " Hydro-Electric Project",
    " Hydropower Project cascade project",
    "HEP", "HPP", "SHP", "HP",
]

def clean_project_name(name: str) -> str:
    """Strip verbose registry suffixes from project names for cleaner slugs."""
    result = (name or "").strip()
    for suffix in PROJECT_SUFFIXES:
        if result.endswith(suffix) and len(result) - len(suffix) >= 3:
            result = result[: -len(suffix)].rstrip()
            break
    return result

def slugify(name: str) -> str:
    """Matches explorer's slug rule for map 'would-be slug'."""
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")


def load_features(manifest: dict, layer_key: str) -> list[dict]:
    layer = manifest["layers"][layer_key]
    path = (SHARED / layer["path"]).resolve()
    gj = json.loads(path.read_text(encoding="utf-8"))
    feats = gj.get("features", [])
    flt = layer.get("filter")
    if flt:
        feats = [ft for ft in feats if (ft.get("properties") or {}).get(flt["field"]) == flt["equals"]]
    return feats


def feature_name(layer_key: str, props: dict) -> str | None:
    """Pick the canonical project name for a feature. hydropower layers use
    'project'; curated layers (watchlist/storage/top) prefer 'project' too,
    fall back to 'label_title'/'name'."""
    for k in ("project", "label_title", "name"):
        v = props.get(k)
        if v:
            return str(v)
    return None


def guess_basin(river: str | None, basin_hint: str | None) -> str | None:
    # Try explicit basin hint first (covers storage-shortlist where 'basin' is set).
    for s in filter(None, (basin_hint, river)):
        haystack = str(s).strip().lower()
        if "koshi" in haystack:   return "koshi-basin"
        if "gandak" in haystack:  return "gandaki-basin"
        if "karnali" in haystack: return "karnali-basin"
        if "mahakali" in haystack or "chameliya" in haystack or "chamliya" in haystack: return "mahakali-basin"
        for needle, slug in BASIN_BY_RIVER:
            if needle in haystack:
                return slug
    return None


def titlecase(name: str) -> str:
    """Light title-casing that preserves acronyms like HEP/HPP/MW and roman numerals."""
    if not name:
        return name
    keep = {"HEP", "HPP", "MW", "I", "II", "III", "IV", "V", "VI", "A", "B"}
    parts = re.split(r"(\s+|-)", name)
    out = []
    for p in parts:
        if p.upper() in keep:
            out.append(p.upper())
        elif p.strip() == "" or p == "-":
            out.append(p)
        else:
            out.append(p[:1].upper() + p[1:])
    return "".join(out)


def fmt_capacity(cap: float | int | None) -> str | None:
    if cap is None or cap == "":
        return None
    try:
        f = float(cap)
        if f == int(f):
            return f"{int(f)} MW"
        return f"{f:g} MW"
    except (TypeError, ValueError):
        return None


def license_human(lt: str | None) -> str:
    m = {"Operation": "Operating", "Generation": "Under construction (Generation licence)", "Survey": "Survey / study"}
    return m.get(lt or "", lt or "—")


def build_tags(layers_in: set[str], props: dict, basin: str | None) -> list[str]:
    tags = ["project"]
    if "priority_watchlist" in layers_in: tags.append("watchlist")
    if "storage_shortlist"  in layers_in: tags.append("storage")
    if "top_capacity"       in layers_in: tags.append("top-capacity")
    lt = (props.get("license_type") or "").lower()
    if lt == "operation":   tags.append("operating")
    elif lt == "generation":tags.append("under-construction")
    elif lt == "survey":    tags.append("survey")
    if basin:
        tags.append(basin.replace("-basin", ""))
    if props.get("district"):
        tags.append(props["district"].lower())
    # dedupe + order
    seen, out = set(), []
    for t in tags:
        if t and t not in seen:
            seen.add(t); out.append(t)
    return out


# --------------------------------------------------------------------------- #
#  Target collection                                                           #
# --------------------------------------------------------------------------- #
def collect_targets(manifest: dict) -> dict[str, dict]:
    """Return: { slug: {
            'name', 'props', 'layers': set[str], 'ids': {layer: [ids]},
            'pri_rank': int, 'source_notes': [str], 'rivers': set, 'basins': set,
        } }
    Merged across every layer the project appears in, with lower-rank layers'
    props winning (watchlist label_title beats a survey-layer typo).
    """
    bundle: dict[str, dict] = {}
    for layer_key, rank, floor in TARGETS:
        feats = load_features(manifest, layer_key)
        for ft in feats:
            p = dict(ft.get("properties") or {})
            name = feature_name(layer_key, p)
            if not name:
                continue
            if floor is not None:
                cap = p.get("capacity_mw") or p.get("installed_mw") or 0
                try:
                    if float(cap) < floor:
                        continue
                except (TypeError, ValueError):
                    continue
            slug = slugify(clean_project_name(name))
            if not slug:
                continue
            entry = bundle.setdefault(slug, {
                "name": name, "props": {}, "layers": set(), "ids": {},
                "pri_rank": rank, "rivers": set(), "basins": set(),
                "source_notes": [],
            })
            entry["layers"].add(layer_key)
            entry["pri_rank"] = min(entry["pri_rank"], rank)
            # merge props: lower rank wins per-key
            for k, v in p.items():
                if v in (None, ""):
                    continue
                existing_rank = entry.setdefault("_rank_for", {}).get(k, 99)
                if rank < existing_rank:
                    entry["props"][k] = v
                    entry["_rank_for"][k] = rank
                elif k not in entry["props"]:
                    entry["props"][k] = v
                    entry["_rank_for"][k] = rank
            fid = p.get("id")
            if fid:
                entry["ids"].setdefault(layer_key, []).append(fid)
            if p.get("river"):   entry["rivers"].add(p["river"])
            if p.get("basin"):   entry["basins"].add(p["basin"])
            if p.get("source_note"):
                entry["source_notes"].append(p["source_note"])
            # use the canonical (lowest-rank) layer's name as display name
            if rank <= entry["pri_rank"]:
                entry["name"] = name
    return bundle


# --------------------------------------------------------------------------- #
#  Stub rendering                                                              #
# --------------------------------------------------------------------------- #
def load_specs_csv() -> dict[str, dict[str, str]]:
    """Read the project specs CSV and return {slug: {column: value}}."""
    import csv as csv_module
    if not SPECS_CSV.exists():
        return {}
    lookup: dict[str, dict[str, str]] = {}
    with SPECS_CSV.open(newline="", encoding="utf-8-sig") as f:
        reader = csv_module.DictReader(f)
        for row in reader:
            slug = (row.get("slug") or "").strip()
            if slug:
                # Filter out None keys (artifacts from trailing commas) and empty values.
                lookup[slug] = {
                    k.strip(): str(v).strip()
                    for k, v in row.items()
                    if k is not None and k.strip() and str(v).strip()
                }
    return lookup


def _render_sectioned_specs(slug: str, specs_lookup: dict[str, dict[str, str]]) -> str | None:
    """Return sectioned spec sub-tables for a slug, or None if no specs exist."""
    if not specs_lookup or slug not in specs_lookup:
        return None
    row = specs_lookup[slug]
    blocks: list[str] = []
    for section_name, fields in SPEC_SECTIONS:
        rows_out: list[str] = []
        for col, label, suffix in fields:
            val = row.get(col)
            if val is None or val == "":
                continue
            # Format display value
            display = val
            try:
                if suffix and "." in val:
                    # Check if it looks like a number with decimal
                    float(val)
            except ValueError:
                pass
            if suffix:
                display = f"{val}{suffix}"
            rows_out.append(f"| {label} | {display} |")
        if rows_out:
            blocks.append(f"### {section_name}\n\n| Parameter | Value |\n|-----------|-------|\n" + "\n".join(rows_out))
    return "\n\n".join(blocks) if blocks else None


def render_spec_block(entry: dict, specs_lookup: dict[str, dict[str, str]] | None = None) -> str:
    p = entry["props"]
    rows: list[tuple[str, str]] = []
    cap = fmt_capacity(p.get("capacity_mw") or p.get("installed_mw"))
    if cap: rows.append(("Capacity", cap))
    if p.get("license_type"):
        rows.append(("Status", license_human(p.get("license_type"))))
    if "storage_shortlist" in entry["layers"] and p.get("category"):
        rows.append(("Category", str(p["category"]).replace("_", " ")))
    if p.get("river"):
        basin = guess_basin(p.get("river"), p.get("basin"))
        river_cell = p["river"]
        if basin:
            river_cell = f"{p['river']} (eastern [[{basin}]])" if basin == "koshi-basin" else f"{p['river']} ([[{basin}]])"
        rows.append(("River", river_cell))
    if p.get("basin") and not p.get("river"):
        basin = guess_basin(None, p.get("basin"))
        rows.append(("Basin", f"{p['basin']} ([[{basin}]])" if basin else str(p["basin"])))
    if p.get("district"):
        rows.append(("District", p["district"].title() if p["district"].isupper() else p["district"]))
    if p.get("province"):
        rows.append(("Province", p["province"]))
    if p.get("annual_energy_gwh"):
        rows.append(("Annual energy", f"{p['annual_energy_gwh']} GWh"))
    if p.get("dry_energy_gwh"):
        rows.append(("Dry-season energy", f"{p['dry_energy_gwh']} GWh"))
    if p.get("dry_share_pct"):
        rows.append(("Dry share", f"{p['dry_share_pct']}%"))
    if p.get("total_storage_mcm"):
        rows.append(("Total storage", f"{p['total_storage_mcm']} MCM"))
    if p.get("effective_storage_mcm"):
        rows.append(("Effective storage", f"{p['effective_storage_mcm']} MCM"))
    if p.get("promoter"):
        rows.append(("Promoter", p["promoter"]))

    lines = [SPEC_START, "", "## Specifications", "", "| Parameter | Value |", "|-----------|-------|"]
    for k, v in rows:
        lines.append(f"| {k} | {v} |")
    lines.append("")

    # Append sectioned specs from the project_specs.csv if available.
    slug = slugify(clean_project_name(entry["name"]))
    sectioned = _render_sectioned_specs(slug, specs_lookup)
    if sectioned:
        lines.append(sectioned)
        lines.append("")

    lines.append(SPEC_END)
    return "\n".join(lines)


def render_stub(slug: str, entry: dict, specs_lookup: dict[str, dict[str, str]] | None = None) -> str:
    p = entry["props"]
    title = titlecase(entry["name"])
    today = dt.date.today().isoformat()
    basin = guess_basin(p.get("river"), p.get("basin"))
    tags = build_tags(entry["layers"], p, basin)

    see_also: list[str] = []
    if basin: see_also.append(basin)
    lt = (p.get("license_type") or "").lower()
    if lt == "operation":
        see_also.append("run-of-river-hydropower")
    if "storage_shortlist" in entry["layers"]:
        see_also += ["storage-deficit", "firm-power"]
    if "priority_watchlist" in entry["layers"]:
        see_also.append("stranded-generation")
    if lt == "survey":
        see_also.append("buildability")
    # dedupe, keep order
    sa_seen, sa_ordered = set(), []
    for s in see_also:
        if s not in sa_seen:
            sa_seen.add(s); sa_ordered.append(s)

    lead_bits = []
    cap = fmt_capacity(p.get("capacity_mw") or p.get("installed_mw"))
    if cap: lead_bits.append(cap)
    lt = p.get("license_type")
    if lt:
        lead_bits.append(license_human(lt).lower())
    elif "storage_shortlist" in entry["layers"]:
        cat = str(p.get("category") or "").replace("_", " ").strip()
        lead_bits.append(cat or "storage candidate")
    if p.get("river"):    lead_bits.append(f"on the {p['river']}")
    elif p.get("basin"):  lead_bits.append(f"in the {p['basin']} basin")
    if p.get("district"): lead_bits.append(f"in {str(p['district']).title() if p['district'].isupper() else p['district']} district")
    lead = " · ".join(lead_bits).rstrip(".") + "."

    # frontmatter — uses block list for images so they're easy to hand-fill.
    fm_lines = [
        "---",
        f'title: {title}',
        "type: entity",
        f"created: {today}",
        f"updated: {today}",
        "sources: []",
        f"tags: [{', '.join(tags)}]",
        "images: []",
        "generator: auto-stub",
        "---",
        "",
        f"# {title}",
        "",
        lead,
        "",
        render_spec_block(entry, specs_lookup),
        "",
        "## Notes",
        "",
        "> [!note] This is a registry-backed project record. Capacity, location,",
        "> and licence status come from the Ministry of Energy registry",
        "> mirrored in the map data. Narrative context and images are added",
        "> where public sources are strong enough; the specification table is",
        "> maintained from the registry.",
        "",
    ]

    if entry["source_notes"]:
        notes = sorted({str(n).strip() for n in entry["source_notes"] if n})
        if notes:
            fm_lines += ["## Registry note", ""]
            for n in notes:
                fm_lines.append(f"- {n}")
            fm_lines.append("")

    if sa_ordered:
        fm_lines += ["## See also", ""]
        for s in sa_ordered:
            fm_lines.append(f"- [[{s}]]")
        fm_lines.append("")

    return "\n".join(fm_lines)


# --------------------------------------------------------------------------- #
#  Bindings sync                                                               #
# --------------------------------------------------------------------------- #
def build_binding_features(entry: dict, canonical_slug: str) -> list[dict]:
    """Shape the feature list the same way existing bindings look."""
    feats: list[dict] = []
    primary_layer = min(entry["layers"], key=lambda k: next(r for _k, r, _ in TARGETS + [(k, 99, None)] if _k == k)) if entry["layers"] else None

    # Curated layers with explicit ids first, primary: true on the best-ranked one.
    for layer_key, rank, _ in TARGETS:
        if layer_key not in entry["layers"]:
            continue
        ids = entry["ids"].get(layer_key, [])
        for fid in ids:
            f = {"layer": layer_key, "id": fid}
            if layer_key == primary_layer:
                f["primary"] = True
            feats.append(f)

    # A single hydropower_points match covers all three hydropower layers
    # (they share the alias). Use the EXACT project string to avoid collisions.
    if any(l.startswith("hydropower_") for l in entry["layers"]):
        exact_name = entry["props"].get("project") or entry["name"]
        feats.append({
            "layer": "hydropower_points",
            "match": {"field": "project", "value": exact_name},
            **({"primary": True} if primary_layer and primary_layer.startswith("hydropower_") else {}),
        })
    return feats


def default_layers_on(entry: dict) -> list[str]:
    base = ["country_outline", "tributaries"]
    if any(l.startswith("hydropower_") for l in entry["layers"]):
        lt = (entry["props"].get("license_type") or "").lower()
        if lt == "operation":   base.append("hydropower_operating")
        elif lt == "generation":base.append("hydropower_construction")
        elif lt == "survey":    base.append("hydropower_survey")
    if "storage_shortlist"  in entry["layers"]: base.append("storage_shortlist")
    if "priority_watchlist" in entry["layers"]: base.append("priority_watchlist")
    if "top_capacity"       in entry["layers"]: base.append("top_capacity")
    # dedupe
    seen, out = set(), []
    for x in base:
        if x not in seen: seen.add(x); out.append(x)
    return out


def sync_bindings(bindings: dict, targets: dict[str, dict], existing_slugs: set[str], write: bool) -> dict:
    """Add entries for slugs that have a file but no binding. Returns stats."""
    pages = bindings.setdefault("pages", {})
    stats = {"added": 0, "already": 0, "aliased_added": 0}
    for raw_slug, entry in targets.items():
        slug = SLUG_ALIASES.get(raw_slug, raw_slug)
        if slug not in existing_slugs and raw_slug not in existing_slugs:
            # we're about to create the stub at slug == raw_slug
            slug = raw_slug
        if slug in pages:
            stats["already"] += 1
            continue
        features = build_binding_features(entry, slug)
        if not features:
            continue
        pages[slug] = {
            "type": "entity",
            "category": "project",
            "features": features,
            "layers_on": default_layers_on(entry),
        }
        if raw_slug in SLUG_ALIASES:
            stats["aliased_added"] += 1
        else:
            stats["added"] += 1
    if write:
        BINDINGS.write_text(json.dumps(bindings, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return stats


# --------------------------------------------------------------------------- #
#  Main                                                                        #
# --------------------------------------------------------------------------- #
def existing_slug_set() -> set[str]:
    out: set[str] = set()
    for cat in ("entities", "concepts", "syntheses", "claims", "sources", "data"):
        d = PAGES / cat
        if d.is_dir():
            for f in d.glob("*.md"):
                out.add(f.stem)
    return out


def is_auto_stub(md_path: Path) -> bool:
    try:
        text = md_path.read_text(encoding="utf-8")
    except OSError:
        return False
    if not text.startswith("---"):
        return False
    end = text.find("\n---", 4)
    if end == -1:
        return False
    return re.search(r"^generator:\s*(auto-stub|specs-refresh)\s*$", text[4:end], re.MULTILINE) is not None


def refresh_spec_block(md_path: Path, entry: dict, specs_lookup: dict[str, dict[str, str]] | None = None) -> bool:
    text = md_path.read_text(encoding="utf-8")
    new_block = render_spec_block(entry, specs_lookup)
    if SPEC_START in text and SPEC_END in text:
        pattern = re.compile(re.escape(SPEC_START) + r".*?" + re.escape(SPEC_END), re.DOTALL)
        new_text = pattern.sub(new_block, text, count=1)
        # also bump `updated:` in frontmatter if present
        new_text = re.sub(r"^updated:\s*.+$", f"updated: {dt.date.today().isoformat()}", new_text, count=1, flags=re.MULTILINE)
        if new_text != text:
            md_path.write_text(new_text, encoding="utf-8")
            return True
    return False


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="Actually write files (default: dry-run)")
    ap.add_argument("--refresh-specs", action="store_true", help="Also refresh generated spec blocks in existing auto-stubs")
    args = ap.parse_args()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    bindings = json.loads(BINDINGS.read_text(encoding="utf-8"))
    existing = existing_slug_set()
    targets = collect_targets(manifest)
    specs_lookup = load_specs_csv()

    print(f"collected {len(targets)} target slugs across {len(TARGETS)} layers")
    print(f"existing wiki pages: {len(existing)}")
    print(f"existing bindings:   {len(bindings.get('pages', {}))}")
    if specs_lookup:
        print(f"specs CSV entries:   {len(specs_lookup)}")

    # Classify
    to_create, to_skip_alias, to_refresh, already_covered = [], [], [], []
    for slug, entry in sorted(targets.items()):
        aliased = SLUG_ALIASES.get(slug)
        if aliased and aliased in existing:
            to_skip_alias.append((slug, aliased)); continue
        if slug in existing:
            path = ENTITIES / f"{slug}.md"
            if is_auto_stub(path):
                to_refresh.append(slug)
            else:
                already_covered.append(slug)
            continue
        to_create.append(slug)

    print()
    print(f"would create:      {len(to_create):4d}")
    print(f"already have page: {len(already_covered):4d}  (hand-written, untouched)")
    print(f"auto-stub (refreshable): {len(to_refresh):4d}")
    print(f"aliased to existing:     {len(to_skip_alias):4d}")
    print()

    if args.write or args.refresh_specs:
        ENTITIES.mkdir(parents=True, exist_ok=True)

    # Create new stubs
    created_count = 0
    if to_create and args.write:
        for slug in to_create:
            path = ENTITIES / f"{slug}.md"
            md = render_stub(slug, targets[slug], specs_lookup)
            path.write_text(md, encoding="utf-8")
            created_count += 1
        print(f"wrote {created_count} new stubs -> wiki/pages/entities/")
    elif to_create:
        print(f"[dry-run] would write {len(to_create)} new stubs. Sample:")
        for slug in to_create[:8]:
            print(f"   - {slug}.md  ({titlecase(targets[slug]['name'])})")
        if len(to_create) > 8: print(f"   ... +{len(to_create)-8} more")

    # Refresh spec blocks in existing auto-stubs
    if args.refresh_specs and to_refresh:
        refreshed = 0
        for slug in to_refresh:
            if refresh_spec_block(ENTITIES / f"{slug}.md", targets[slug], specs_lookup):
                refreshed += 1
        print(f"refreshed spec block in {refreshed}/{len(to_refresh)} auto-stubs")

    # Update bindings (only for files that now exist)
    existing_after = existing_slug_set() if args.write else (existing | set(to_create))
    stats = sync_bindings(bindings, targets, existing_after, write=args.write)
    print(f"bindings: {stats['added']} new (+{stats['aliased_added']} aliased), {stats['already']} already present")
    if not args.write:
        print("\n[dry-run] rerun with --write to apply.")
        return 0

    # Rebuild the static indexes the explorer reads. Order matters:
    # backlinks depend on the page index, so run the index builder first.
    for script in (
        "build_wiki_page_index.py",
        "build_wiki_page_meta.py",
        "build_backlinks.py",
    ):
        print(f"--> {script}")
        subprocess.run([sys.executable, str(ROOT / "scripts" / script)], check=True, cwd=ROOT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
