// Wiki page loader: finds page across category folders, parses frontmatter, renders markdown,
// rewrites [[wikilinks]] to functioning links and tags spatial ones.
(function () {
if (window.NepalExplorer && window.NepalExplorer._wikiLoaderLoaded) return;

const PAGE_DIRS = ["sources", "entities", "concepts", "syntheses", "claims", "data"];

const PAGE_INDEX_CACHE = { built: false, byCategory: {}, allSlugs: [], slugToCategory: {}, slugToTitle: {} };
const BACKLINKS_CACHE = { built: false, map: {} };

// Cache-bust JSON fetches so stub regeneration (which rewrites
// wiki-page-index.json) propagates without requiring a hard reload.
const _WL_CB = (() => {
  try {
    const m = document.querySelector('meta[name="np-build"]');
    if (m && m.content) return m.content;
  } catch (e) {}
  return String(Date.now());
})();
const loadJSON = (path) => {
  const url = path + (path.includes("?") ? "&" : "?") + "cb=" + _WL_CB;
  return fetch(url).then((r) => { if (!r.ok) throw new Error(path); return r.json(); });
};

async function buildPageIndex() {
  if (PAGE_INDEX_CACHE.built) return PAGE_INDEX_CACHE;
  // Static manifest -- generated by scripts/build_wiki_page_index.py.
  // Falls back to a runtime probe if missing.
  try {
    const m = await loadJSON("shared/wiki-page-index.json");
    PAGE_INDEX_CACHE.byCategory = m.byCategory;
    PAGE_INDEX_CACHE.allSlugs = m.allSlugs;
    PAGE_INDEX_CACHE.slugToCategory = m.slugToCategory;
    PAGE_INDEX_CACHE.slugToTitle = m.slugToTitle;
    PAGE_INDEX_CACHE.built = true;
    return PAGE_INDEX_CACHE;
  } catch (e) {
    console.warn("page index missing, run build_wiki_page_index.py", e);
    return PAGE_INDEX_CACHE;
  }
}

async function loadBacklinks() {
  if (BACKLINKS_CACHE.built) return BACKLINKS_CACHE;
  try {
    const data = await loadJSON("shared/wiki-backlinks.json");
    BACKLINKS_CACHE.map = data.backlinks || {};
    BACKLINKS_CACHE.built = true;
  } catch (e) {
    // Non-fatal: wiki-backlinks.json is optional. Reader just won't
    // show a "Referenced by" section.
    console.warn("backlinks missing, run build_backlinks.py", e);
    BACKLINKS_CACHE.built = true;
  }
  return BACKLINKS_CACHE;
}

function renderBacklinks(slug, idx, spatialSlugs) {
  const refs = (BACKLINKS_CACHE.map || {})[slug] || [];
  if (!refs.length) return "";
  // Group by category so the footer reads: "3 entities, 2 concepts, ...".
  const byCat = {};
  for (const r of refs) {
    (byCat[r.category] = byCat[r.category] || []).push(r);
  }
  const CAT_LABEL = {
    entities: "Entities",
    concepts: "Concepts",
    syntheses: "Syntheses",
    claims: "Claims",
    sources: "Sources",
    data: "Data",
  };
  const parts = [];
  for (const cat of ["entities", "syntheses", "concepts", "claims", "sources", "data"]) {
    const items = byCat[cat];
    if (!items || !items.length) continue;
    const rows = items.map((r) => {
      const sp = spatialSlugs && spatialSlugs.has(r.slug) ? " spatial" : "";
      return `<li class="backlink-item">
        <a class="wikilink${sp}" href="javascript:void(0)" onclick="window.openWikiPage && window.openWikiPage('${r.slug}')">${r.title}</a>
        <div class="backlink-context">${r.context.replace(/</g, "&lt;")}</div>
      </li>`;
    }).join("");
    parts.push(
      `<div class="backlinks-group"><div class="backlinks-cat">${CAT_LABEL[cat] || cat} <span class="backlinks-count">${items.length}</span></div><ul class="backlinks-list">${rows}</ul></div>`
    );
  }
  return `<section class="backlinks-section"><h2 class="backlinks-heading">Referenced by <span class="backlinks-total">${refs.length}</span></h2>${parts.join("")}</section>`;
}

async function fetchPageMarkdown(slug) {
  const idx = await buildPageIndex();
  const cat = idx.slugToCategory[slug];
  if (!cat) {
    return { found: false, raw: `No page for **${slug}**.` };
  }
  const path = `../pages/${cat}/${slug}.md`;
  const r = await fetch(path + "?cb=" + _WL_CB);
  if (!r.ok) return { found: false, raw: `Could not load ${path}` };
  const raw = await r.text();
  return { found: true, raw, path, category: cat };
}

function splitFrontmatter(md) {
  if (!md.startsWith("---\n")) return { frontmatter: "", body: md };
  const end = md.indexOf("\n---", 4);
  if (end === -1) return { frontmatter: "", body: md };
  const fm = md.substring(4, end).trim();
  const body = md.substring(end + 4).replace(/^\n+/, "");
  return { frontmatter: fm, body };
}

// Parse the `images:` block from YAML frontmatter without pulling a YAML lib.
// Accepts either an empty inline list (`images: []`) or an indented block
// list of `- key: value` items. Unknown keys on items are preserved.
function parseImagesFromFrontmatter(fm) {
  if (!fm) return [];
  const lines = fm.split(/\r?\n/);
  let inside = false;
  let curr = null;
  const out = [];
  const push = () => { if (curr && curr.src) out.push(curr); curr = null; };
  for (const line of lines) {
    const emptyInline = /^images\s*:\s*\[\s*\]\s*$/.test(line);
    const blockStart  = /^images\s*:\s*$/.test(line);
    if (emptyInline) { inside = false; continue; }
    if (blockStart)  { inside = true;  continue; }
    if (inside) {
      // Top-level key (not indented) ends the block.
      if (/^[A-Za-z_][\w-]*\s*:/.test(line)) { push(); inside = false; continue; }
      const item = line.match(/^\s*-\s+(\w+)\s*:\s*(.*)$/);
      if (item) {
        push();
        curr = {};
        curr[item[1]] = item[2].trim().replace(/^['"]|['"]$/g, "");
        continue;
      }
      const kv = line.match(/^\s+(\w+)\s*:\s*(.*)$/);
      if (kv && curr) curr[kv[1]] = kv[2].trim().replace(/^['"]|['"]$/g, "");
    }
  }
  push();
  return out;
}

// Render a horizontal filmstrip above the page body. Thumbs lazy-load and
// quietly hide if the asset is missing so empty `images: []` stubs stay clean.
function renderFilmstrip(images) {
  if (!images || !images.length) return "";
  const esc = (s) => String(s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const items = images.map((img, i) => {
    const src = `../assets/images/${img.src}`;
    const cap = esc(img.caption || "");
    const cred = img.credit ? `<span class="wiki-thumb-credit">${esc(img.credit)}${img.license ? ` · ${esc(img.license)}` : ""}</span>` : "";
    return `<figure class="wiki-thumb" tabindex="0" onclick="window.openWikiLightbox && window.openWikiLightbox(${i})" data-src="${esc(src)}" data-caption="${cap}" data-credit="${esc(img.credit || "")}" data-license="${esc(img.license || "")}">
      <img loading="lazy" src="${esc(src)}" alt="${cap}" onerror="this.parentNode.classList.add('broken')"/>
      <figcaption>${cap}${cred}</figcaption>
    </figure>`;
  }).join("");
  return `<div class="wiki-filmstrip" data-count="${images.length}">${items}</div>`;
}

function rewriteWikilinks(html, slugIndex, spatialSlugs, onClickAttr = "openWikiPage") {
  return html.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, label) => {
    const slug = target.trim();
    const text = (label || slug).trim();
    const known = slugIndex.allSlugs && slugIndex.allSlugs.includes(slug);
    const klass = ["wikilink"];
    if (!known) klass.push("broken");
    if (spatialSlugs && spatialSlugs.has(slug)) klass.push("spatial");
    return `<a class="${klass.join(" ")}" href="javascript:void(0)" onclick="window.${onClickAttr} && window.${onClickAttr}('${slug}')">${text}</a>`;
  });
}

async function renderPage(slug, opts = {}) {
  // opts.spatialSlugs Set, opts.bindings, opts.showFrontmatter
  const [idx] = await Promise.all([buildPageIndex(), loadBacklinks()]);
  const { found, raw, category } = await fetchPageMarkdown(slug);
  if (!found) {
    return `<div class="placeholder">${raw}</div>`;
  }
  const { frontmatter, body } = splitFrontmatter(raw);
  const images = parseImagesFromFrontmatter(frontmatter);
  const html = window.marked ? marked.parse(body) : `<pre>${body}</pre>`;
  const linked = rewriteWikilinks(html, idx, opts.spatialSlugs);
  const fm = opts.showFrontmatter ? `<pre class="frontmatter show">${frontmatter}</pre>` : "";
  const cat = `<div style="font-family: var(--sans); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--ink-soft); margin-bottom: 6px;">${category} · ${slug}</div>`;
  // Stash images on the page element via a data attribute so the lightbox
  // handler can read them without a global.
  const filmstrip = renderFilmstrip(images);
  const imageData = images.length
    ? `<script type="application/json" id="wiki-images-data">${JSON.stringify(images).replace(/</g, "\\u003c")}</script>`
    : "";
  const backlinks = renderBacklinks(slug, idx, opts.spatialSlugs);
  return cat + fm + filmstrip + imageData + linked + backlinks;
}

window.NepalExplorer = window.NepalExplorer || {};
Object.assign(window.NepalExplorer, { buildPageIndex, fetchPageMarkdown, renderPage, splitFrontmatter, rewriteWikilinks, parseImagesFromFrontmatter, loadBacklinks });
window.NepalExplorer._wikiLoaderLoaded = true;
})();
