// Wiki page loader: finds page across category folders, parses frontmatter, renders markdown,
// rewrites [[wikilinks]] to functioning links and tags spatial ones.
(function () {
if (window.NepalExplorer && window.NepalExplorer._wikiLoaderLoaded) return;

function sanitizeHTML(html) {
  return String(html)
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "")
    .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, "")
    .replace(/<object\b[^<]*(?:(?!<\/object>)<[^<]*)*<\/object>/gi, "")
    .replace(/<embed\b[^<]*(?:(?!<\/embed>)<[^<]*)*<\/embed>/gi, "")
    .replace(/\son\w+\s*=\s*"[^"]*"/gi, "")
    .replace(/\son\w+\s*=\s*'[^']*'/gi, "")
    .replace(/javascript\s*:/gi, "blocked:");
}

const PAGE_DIRS = ["sources", "entities", "concepts", "syntheses", "claims", "data", "interventions"];

const PAGE_INDEX_CACHE = { built: false, byCategory: {}, allSlugs: [], slugToCategory: {}, slugToTitle: {} };
const BACKLINKS_CACHE = { built: false, map: {} };
const CLAIM_GOVERNANCE_CACHE = { built: false, bySlug: {} };

function wikiPageHref(slug) {
  const cleanRoutes = new Set(window.__WIKI_CLEAN_ROUTE_SLUGS__ || []);
  return cleanRoutes.has(slug)
    ? `/wiki/${encodeURIComponent(slug)}/`
    : `/wiki/explorer/?page=${encodeURIComponent(slug)}`;
}

function wikiPageLinkAttrs(slug, onClickAttr = "openWikiPage") {
  const cleanRoutes = new Set(window.__WIKI_CLEAN_ROUTE_SLUGS__ || []);
  const href = wikiPageHref(slug);
  if (cleanRoutes.has(slug)) return `href="${escapeHtml(href)}"`;
  return `href="${escapeHtml(href)}" onclick="event.preventDefault(); window.${onClickAttr} && window.${onClickAttr}('${escapeHtml(slug)}')"`;
}

// Cache-bust JSON fetches with the release token instead of per-page-load
// timestamps so production browsers can reuse wiki metadata across reloads.
const _WL_CB = (() => {
  try {
    const m = document.querySelector('meta[name="np-build"]');
    if (m && m.content) return m.content;
  } catch (e) {}
  return "public-launch-5";
})();
const loadJSON = (path) => {
  const url = path + (path.includes("?") ? "&" : "?") + "cb=" + _WL_CB;
  return fetch(url).then((r) => { if (!r.ok) throw new Error(path); return r.json(); });
};

async function buildPageIndex() {
  if (PAGE_INDEX_CACHE.built) return PAGE_INDEX_CACHE;
  // Static manifest -- generated by scripts/build_wiki_page_index.py.
  // Falls back to a runtime probe if missing.
  try {
    const m = await loadJSON("shared/wiki-page-index.json");
    PAGE_INDEX_CACHE.byCategory = m.byCategory;
    PAGE_INDEX_CACHE.allSlugs = m.allSlugs;
    PAGE_INDEX_CACHE.slugToCategory = m.slugToCategory;
    PAGE_INDEX_CACHE.slugToTitle = m.slugToTitle;
    PAGE_INDEX_CACHE.built = true;
    return PAGE_INDEX_CACHE;
  } catch (e) {
    console.warn("page index missing, run build_wiki_page_index.py", e);
    return PAGE_INDEX_CACHE;
  }
}

async function loadBacklinks() {
  if (BACKLINKS_CACHE.built) return BACKLINKS_CACHE;
  try {
    const data = await loadJSON("shared/wiki-backlinks.json");
    BACKLINKS_CACHE.map = data.backlinks || {};
    BACKLINKS_CACHE.built = true;
  } catch (e) {
    // Non-fatal: wiki-backlinks.json is optional. Reader just won't
    // show a "Referenced by" section.
    console.warn("backlinks missing, run build_backlinks.py", e);
    BACKLINKS_CACHE.built = true;
  }
  return BACKLINKS_CACHE;
}

async function loadClaimGovernance() {
  if (CLAIM_GOVERNANCE_CACHE.built) return CLAIM_GOVERNANCE_CACHE;
  try {
    const data = await loadJSON("shared/claim-governance.json");
    CLAIM_GOVERNANCE_CACHE.bySlug = data.bySlug || {};
  } catch (e) {
    // Optional prototype metadata. Claim pages render normally without it.
    CLAIM_GOVERNANCE_CACHE.bySlug = {};
  }
  CLAIM_GOVERNANCE_CACHE.built = true;
  return CLAIM_GOVERNANCE_CACHE;
}

function renderBacklinks(slug, idx, spatialSlugs, options = {}) {
  const refs = (BACKLINKS_CACHE.map || {})[slug] || [];
  const renderer = window.NepalExplorer && window.NepalExplorer.renderReferenceSection;
  if (renderer) return renderer(refs, { ...options, spatialSlugs });
  return "";
}

function escapeHtml(s) {
  return String(s || "").replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&#39;" }[c]));
}

function unquoteFrontmatterValue(value) {
  const text = String(value || "").trim();
  if ((text.startsWith('"') && text.endsWith('"')) || (text.startsWith("'") && text.endsWith("'"))) {
    return text.slice(1, -1).trim();
  }
  return text;
}

function frontmatterScalar(frontmatter, key) {
  const escaped = String(key).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = String(frontmatter || "").match(new RegExp(`^${escaped}:\\s*(.+?)\\s*$`, "m"));
  return match ? unquoteFrontmatterValue(match[1]) : "";
}

function frontmatterList(frontmatter, key) {
  const escaped = String(key).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const text = String(frontmatter || "");
  const inline = text.match(new RegExp(`^${escaped}:\\s*\\[([^\\]]*)\\]\\s*$`, "m"));
  if (inline) {
    return inline[1].split(",").map(unquoteFrontmatterValue).filter(Boolean);
  }
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((line) => new RegExp(`^${escaped}:\\s*$`).test(line));
  if (start < 0) return [];
  const values = [];
  for (let i = start + 1; i < lines.length; i++) {
    const item = lines[i].match(/^\s+-\s+(.+?)\s*$/);
    if (!item) break;
    values.push(unquoteFrontmatterValue(item[1]));
  }
  return values.filter(Boolean);
}

function publicMaturity(frontmatter) {
  const explicit = frontmatterScalar(frontmatter, "maturity");
  if (["verified-core", "working-page", "registry-record"].includes(explicit)) return explicit;
  const quality = frontmatterScalar(frontmatter, "page_quality");
  const generator = frontmatterScalar(frontmatter, "generator");
  if (quality === "flagship") return "verified-core";
  if (quality === "record" || generator === "auto-stub") return "registry-record";
  return "working-page";
}

const MATURITY_LABEL = {
  "verified-core": "Verified Core",
  "working-page": "Working Page",
  "registry-record": "Registry Record",
};

const MATURITY_HELP = {
  "verified-core": "Core page that passed evidence and editorial review; individual caveats still apply.",
  "working-page": "Useful analysis or explanation that remains open to further evidence and editorial development.",
  "registry-record": "Basic factual record; inclusion does not mean every status or technical field has been independently verified.",
};

function todayIsoDate() {
  const now = new Date();
  const local = new Date(now.getTime() - now.getTimezoneOffset() * 60000);
  return local.toISOString().slice(0, 10);
}

function renderPageStatus(frontmatter) {
  const maturity = publicMaturity(frontmatter);
  const updated = frontmatterScalar(frontmatter, "updated");
  const asOf = frontmatterScalar(frontmatter, "as_of");
  const reviewed = frontmatterScalar(frontmatter, "reviewed");
  const verifiedOn = frontmatterScalar(frontmatter, "verified_on");
  const reviewDue = frontmatterScalar(frontmatter, "review_due");
  const caveat = frontmatterScalar(frontmatter, "caveat") || frontmatterScalar(frontmatter, "verification_note");
  const facts = [];
  if (updated) facts.push(`Updated ${escapeHtml(updated)}`);
  if (asOf) facts.push(`Evidence as of ${escapeHtml(asOf)}`);
  if (reviewed) facts.push(`Reviewed ${escapeHtml(reviewed)}`);
  else if (verifiedOn) facts.push(`Verified ${escapeHtml(verifiedOn)}`);
  const overdue = /^\d{4}-\d{2}-\d{2}$/.test(reviewDue) && reviewDue < todayIsoDate();
  if (reviewDue) facts.push(`${overdue ? "Review overdue" : "Review due"} ${escapeHtml(reviewDue)}`);
  const line = `<div class="wiki-page-status">
    ${facts.length ? `<span class="wiki-status-dates">${facts.join(" · ")}</span>` : ""}
    <span class="maturity-chip maturity-${maturity}" title="${escapeHtml(MATURITY_HELP[maturity])}">${MATURITY_LABEL[maturity]}</span>
    ${overdue ? `<span class="freshness-alert">Review overdue</span>` : ""}
  </div>`;
  const caveatHtml = caveat
    ? `<aside class="wiki-caveat"><b>Current caveat</b><span>${escapeHtml(caveat)}</span></aside>`
    : "";
  return { line, caveatHtml, maturity };
}

function publicAssetPath(value) {
  let path = String(value || "")
    .trim()
    .replace(/[?#].*$/, "")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "");
  while (path.startsWith("../")) path = path.slice(3);
  if (path.startsWith("./")) path = path.slice(2);
  return path;
}

function isOmittedPublicAsset(value) {
  return publicAssetPath(value).startsWith("data/raw/");
}

function safeSourceHref(value) {
  const href = String(value || "").trim();
  if (/^https?:\/\//i.test(href)) return href;
  if (isOmittedPublicAsset(href)) return "";
  if (/^(?:\.\.\/|\.\/|\/)[^<>"']+$/.test(href)) return href;
  return "";
}

function humanize(value) {
  return String(value || "").replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function renderSourceProvenance(frontmatter) {
  const sourceType = frontmatterScalar(frontmatter, "source_type");
  const author = frontmatterScalar(frontmatter, "source_author") || frontmatterScalar(frontmatter, "publisher");
  const sourceDate = frontmatterScalar(frontmatter, "source_date");
  const sourceUrl = frontmatterScalar(frontmatter, "source_url");
  const authority = frontmatterScalar(frontmatter, "source_authority");
  const access = frontmatterScalar(frontmatter, "source_access");
  const verifiedOn = frontmatterScalar(frontmatter, "verified_on");
  const reviewed = frontmatterScalar(frontmatter, "reviewed");
  const caveat = frontmatterScalar(frontmatter, "caveat") || frontmatterScalar(frontmatter, "verification_note");
  const href = safeSourceHref(sourceUrl);
  const isExternal = /^https?:\/\//i.test(href);
  const isOmittedLocal = Boolean(sourceUrl)
    && !/^https?:\/\//i.test(sourceUrl)
    && isOmittedPublicAsset(sourceUrl);
  const cells = [
    ["Type", sourceType ? humanize(sourceType) : "Not recorded"],
    ["Author / publisher", author || "Not recorded"],
    ["Publication date", sourceDate || "Not recorded"],
    ["Authority", authority ? humanize(authority) : "Not classified"],
    ["Evidence checked", verifiedOn || reviewed || "No separate verification date"],
  ];
  let accessText = access ? humanize(access) : "";
  if (isOmittedLocal) {
    accessText = accessText
      ? `${accessText} · Asset not included in public release`
      : "Local archive reference · Asset not included in public release";
  } else if (!accessText) {
    accessText = sourceUrl ? (isExternal ? "Public external link" : "Local archive path") : "No direct link recorded";
  }
  return `<aside class="provenance-card source-provenance-card" aria-label="Source provenance">
    <div class="provenance-kicker">Source provenance</div>
    <div class="provenance-grid">${cells.map(([label, value]) => `<div><span>${escapeHtml(label)}</span><b>${escapeHtml(value)}</b></div>`).join("")}</div>
    <div class="provenance-access"><span>${escapeHtml(accessText)}</span>${href ? `<a href="${escapeHtml(href)}" ${isExternal ? 'target="_blank" rel="noopener noreferrer"' : ""}>Open source</a>` : ""}</div>
    ${caveat ? `<div class="provenance-caveat"><b>Caveat:</b> ${escapeHtml(caveat)}</div>` : ""}
  </aside>`;
}

function wikiPageLink(slug, title) {
  return `<a class="evidence-source-link" ${wikiPageLinkAttrs(slug)}>${escapeHtml(title || slug)}</a>`;
}

function renderClaimGovernance(slug, frontmatter = "", idx = PAGE_INDEX_CACHE) {
  const entry = (CLAIM_GOVERNANCE_CACHE.bySlug || {})[slug];
  const metrics = entry && Array.isArray(entry.metrics) ? entry.metrics.slice(0, 6) : [];
  const metricRows = metrics.map((m) => {
    const source = m.source_slug
      ? wikiPageLink(m.source_slug, (idx.slugToTitle && idx.slugToTitle[m.source_slug]) || m.source_slug)
      : "";
    return `<li>
      <span class="cg-metric-name">${escapeHtml(m.name || m.id || "Metric")}</span>
      <span class="cg-metric-value">${escapeHtml(m.value || "")}</span>
      ${source}
    </li>`;
  }).join("");
  const tier = entry ? (entry.tier === "core" ? "Core claim" : "Supporting claim") : "Page claim";
  const count = metrics.length === 1 ? "1 tracked metric" : `${metrics.length} tracked metrics`;
  const summary = metrics.length
    ? `${count} checked against the claim registry.`
    : entry
      ? "Registered in the claim registry; no numeric metric anchors are required yet."
      : "No governed numeric metric is registered for this page.";
  const sourceSlugs = frontmatterList(frontmatter, "sources");
  const sourceLinks = sourceSlugs.map((sourceSlug) => wikiPageLink(sourceSlug, (idx.slugToTitle && idx.slugToTitle[sourceSlug]) || sourceSlug)).join("");
  const confidence = frontmatterScalar(frontmatter, "confidence") || "Not recorded";
  const status = frontmatterScalar(frontmatter, "status") || "Not recorded";
  const verifiedOn = frontmatterScalar(frontmatter, "verified_on");
  const reviewed = frontmatterScalar(frontmatter, "reviewed");
  const reviewDue = frontmatterScalar(frontmatter, "review_due");
  const claimId = frontmatterScalar(frontmatter, "claim_id") || (entry && entry.claim_id) || "";
  return `<aside class="claim-governance-card" aria-label="Claim evidence">
    <button type="button" class="cg-info" aria-label="What is a governed claim?">
      <svg viewBox="0 0 20 20" aria-hidden="true" focusable="false">
        <circle cx="10" cy="10" r="8.25"></circle>
        <path d="M10 8.8v5"></path>
        <path d="M10 5.9h.01"></path>
      </svg>
      <span class="cg-tooltip" role="tooltip">${entry
        ? "This claim is tied to a registry of load-bearing evidence. Listed metric values are checked by validation so stale or conflicting numbers are caught before publishing."
        : "This page lists its evidence links and review metadata. It does not currently have governed numeric metrics in the claim registry."
      }</span>
    </button>
    <div class="cg-topline">
      <span class="cg-badge">${entry ? "Governed claim" : "Claim evidence"}</span>
      <span>${escapeHtml(tier)}${claimId ? ` · ${escapeHtml(claimId)}` : ""}</span>
    </div>
    <div class="claim-status-grid">
      <span><small>Confidence</small><b>${escapeHtml(humanize(confidence))}</b></span>
      <span><small>Status</small><b>${escapeHtml(humanize(status))}</b></span>
      <span><small>Evidence checked</small><b>${escapeHtml(verifiedOn || reviewed || "No separate date")}</b></span>
      <span><small>Review due</small><b>${escapeHtml(reviewDue || "Not scheduled")}</b></span>
    </div>
    <div class="cg-title">${escapeHtml(summary)}</div>
    <div class="claim-source-list"><b>Evidence sources</b>${sourceLinks || `<span class="evidence-missing">No source links recorded.</span>`}</div>
    ${metricRows ? `<ul class="cg-metrics">${metricRows}</ul>` : ""}
  </aside>`;
}

function decorateHeadingsAndBuildToc(html) {
  if (typeof document === "undefined") return { html, toc: "" };
  const template = document.createElement("template");
  template.innerHTML = String(html || "");
  const headings = Array.from(template.content.querySelectorAll("h2, h3"));
  const h2Count = headings.filter((heading) => heading.tagName === "H2").length;
  if (h2Count < 3) return { html: template.innerHTML, toc: "" };
  const used = new Set();
  const links = headings.slice(0, 18).map((heading, index) => {
    const label = String(heading.textContent || "").replace(/\s+/g, " ").trim();
    if (!label) return "";
    let base = label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || `section-${index + 1}`;
    let id = `wiki-${base}`;
    let suffix = 2;
    while (used.has(id)) id = `wiki-${base}-${suffix++}`;
    used.add(id);
    heading.id = id;
    heading.classList.add("wiki-section-heading");
    return `<a class="toc-${heading.tagName.toLowerCase()}" href="#${escapeHtml(id)}">${escapeHtml(label)}</a>`;
  }).filter(Boolean);
  const toc = `<details class="wiki-toc" open><summary>On this page</summary><nav>${links.join("")}</nav></details>`;
  return { html: template.innerHTML, toc };
}

function insertAfterLeadHeading(html, addition) {
  if (!addition) return html;
  const match = String(html || "").match(/<h1\b[^>]*>[\s\S]*?<\/h1>/i);
  if (!match) return addition + html;
  const end = match.index + match[0].length;
  return html.slice(0, end) + addition + html.slice(end);
}

async function fetchPageMarkdown(slug) {
  const idx = await buildPageIndex();
  const cat = idx.slugToCategory[slug];
  if (!cat) {
    return { found: false, raw: `No page for **${slug}**.` };
  }
  const path = `../pages/${cat}/${slug}.md`;
  const r = await fetch(path + "?cb=" + _WL_CB);
  if (!r.ok) return { found: false, raw: `Could not load ${path}` };
  const raw = await r.text();
  return { found: true, raw, path, category: cat };
}

function splitFrontmatter(md) {
  if (!md.startsWith("---\n")) return { frontmatter: "", body: md };
  const end = md.indexOf("\n---", 4);
  if (end === -1) return { frontmatter: "", body: md };
  const fm = md.substring(4, end).trim();
  const body = md.substring(end + 4).replace(/^\n+/, "");
  return { frontmatter: fm, body };
}

// Parse the `images:` block from YAML frontmatter without pulling a YAML lib.
// Accepts either an empty inline list (`images: []`) or an indented block
// list of `- key: value` items. Unknown keys on items are preserved.
function parseImagesFromFrontmatter(fm) {
  if (!fm) return [];
  const lines = fm.split(/\r?\n/);
  let inside = false;
  let curr = null;
  const out = [];
  const push = () => { if (curr && curr.src) out.push(curr); curr = null; };
  for (const line of lines) {
    const emptyInline = /^images\s*:\s*\[\s*\]\s*$/.test(line);
    const blockStart  = /^images\s*:\s*$/.test(line);
    if (emptyInline) { inside = false; continue; }
    if (blockStart)  { inside = true;  continue; }
    if (inside) {
      // Top-level key (not indented) ends the block.
      if (/^[A-Za-z_][\w-]*\s*:/.test(line)) { push(); inside = false; continue; }
      const item = line.match(/^\s*-\s+(\w+)\s*:\s*(.*)$/);
      if (item) {
        push();
        curr = {};
        curr[item[1]] = item[2].trim().replace(/^['"]|['"]$/g, "");
        continue;
      }
      const kv = line.match(/^\s+(\w+)\s*:\s*(.*)$/);
      if (kv && curr) curr[kv[1]] = kv[2].trim().replace(/^['"]|['"]$/g, "");
    }
  }
  push();
  return out;
}

// Render a horizontal filmstrip above the page body. Thumbs lazy-load and
// quietly hide if the asset is missing so empty `images: []` stubs stay clean.
function renderFilmstrip(images) {
  if (!images || !images.length) return "";
  const esc = (s) => String(s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const items = images.map((img, i) => {
    const src = `../assets/images/${img.src}`;
    const cap = esc(img.caption || "");
    const cred = img.credit ? `<span class="wiki-thumb-credit">${esc(img.credit)}${img.license ? ` · ${esc(img.license)}` : ""}</span>` : "";
    return `<figure class="wiki-thumb" tabindex="0" onclick="window.openWikiLightbox && window.openWikiLightbox(${i})" data-src="${esc(src)}" data-caption="${cap}" data-credit="${esc(img.credit || "")}" data-license="${esc(img.license || "")}">
      <img loading="lazy" src="${esc(src)}" alt="${cap}" onerror="this.parentNode.classList.add('broken')"/>
      <figcaption>${cap}${cred}</figcaption>
    </figure>`;
  }).join("");
  return `<div class="wiki-filmstrip" data-count="${images.length}">${items}</div>`;
}

function rewriteWikilinks(html, slugIndex, spatialSlugs, onClickAttr = "openWikiPage") {
  return html.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, label) => {
    const slug = target.trim();
    const text = (label || slug).trim();
    const known = slugIndex.allSlugs && slugIndex.allSlugs.includes(slug);
    const klass = ["wikilink"];
    if (!known) klass.push("broken");
    if (spatialSlugs && spatialSlugs.has(slug)) klass.push("spatial");
    return `<a class="${klass.join(" ")}" ${wikiPageLinkAttrs(slug, onClickAttr)}>${text}</a>`;
  });
}

function renderCallouts(html) {
  const labels = {
    note: "Note",
    warning: "Caution",
    contradiction: "Conflicting sources",
    gap: "Evidence gap",
    cite: "Source note",
    finding: "Finding",
  };
  return html.replace(
    /<blockquote>\s*<p>\[!(note|warning|contradiction|gap|cite|finding)\]\s*([\s\S]*?)<\/p>\s*<\/blockquote>/gi,
    (_, typeRaw, body) => {
      const type = String(typeRaw).toLowerCase();
      return `<aside class="wiki-callout wiki-callout-${type}"><div class="wiki-callout-label">${labels[type] || "Note"}</div><div class="wiki-callout-body">${body.trim()}</div></aside>`;
    }
  );
}

async function renderPage(slug, opts = {}) {
  // opts.spatialSlugs Set, opts.bindings, opts.showFrontmatter
  const [idx] = await Promise.all([buildPageIndex(), loadBacklinks(), loadClaimGovernance()]);
  const { found, raw, category } = await fetchPageMarkdown(slug);
  if (!found) {
    return `<div class="placeholder">${raw}</div>`;
  }
  const { frontmatter, body } = splitFrontmatter(raw);
  const images = parseImagesFromFrontmatter(frontmatter);
  const rawHtml = window.marked ? marked.parse(body) : `<pre>${body}</pre>`;
  const html = sanitizeHTML(rawHtml);
  const linked = renderCallouts(rewriteWikilinks(html, idx, opts.spatialSlugs));
  const fm = opts.showFrontmatter ? `<pre class="frontmatter show">${frontmatter}</pre>` : "";
  // Superseded-by banner — points readers to the richer page.
  const supMatch = body.match(/<!--\s*superseded-by:\s*(\S+)\s*-->/);
  let supersededBanner = "";
  if (supMatch) {
    const target = supMatch[1];
    const targetTitle = (idx.slugToTitle && idx.slugToTitle[target]) || target;
    supersededBanner = `<aside class="wiki-callout wiki-callout-note" style="margin-bottom:16px">
      <div class="wiki-callout-label">Updated page available</div>
      <div class="wiki-callout-body">A more detailed page for this project exists: <a class="wikilink" ${wikiPageLinkAttrs(target)}>${targetTitle}</a></div>
    </aside>`;
  }

  const pageStatus = renderPageStatus(frontmatter);
  const categoryLabel = category === "interventions" ? "Decision Dossier" : category;
  const catWithFreshness = `<div class="wiki-page-identity">${escapeHtml(categoryLabel)} · ${escapeHtml(slug)}</div>${pageStatus.line}`;
  // Stash images on the page element via a data attribute so the lightbox
  // handler can read them without a global.
  const filmstrip = renderFilmstrip(images);
  const imageData = images.length
    ? `<script type="application/json" id="wiki-images-data">${JSON.stringify(images).replace(/</g, "\\u003c")}</script>`
    : "";
  const sourceProvenance = category === "sources" ? renderSourceProvenance(frontmatter) : "";
  const claimGovernance = category === "claims" ? renderClaimGovernance(slug, frontmatter, idx) : "";
  const decorated = decorateHeadingsAndBuildToc(linked);
  // Source cards already carry their caveat; avoid repeating the same warning
  // immediately below the card while retaining the header freshness line.
  const inlineCaveat = category === "sources" ? "" : pageStatus.caveatHtml;
  const readerCards = sourceProvenance + claimGovernance + inlineCaveat + decorated.toc;
  const readerBody = insertAfterLeadHeading(decorated.html, readerCards);
  const backlinks = renderBacklinks(slug, idx, opts.spatialSlugs, {
    heading: category === "sources" ? "Used By" : "Referenced by",
  });
  return catWithFreshness + supersededBanner + fm + filmstrip + imageData + readerBody + backlinks;
}

window.NepalExplorer = window.NepalExplorer || {};
Object.assign(window.NepalExplorer, { buildPageIndex, fetchPageMarkdown, renderPage, splitFrontmatter, rewriteWikilinks, renderCallouts, parseImagesFromFrontmatter, frontmatterScalar, frontmatterList, publicMaturity, renderPageStatus, renderSourceProvenance, renderClaimGovernance, decorateHeadingsAndBuildToc, loadBacklinks, loadClaimGovernance, wikiPageHref, wikiPageLinkAttrs });
window.NepalExplorer._wikiLoaderLoaded = true;
})();
